on:
  push:
    branches:
      - main


jobs:

  docs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Make sure we get all refs
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19.2

      - run: pip install -r requirements.txt

      - run: make html
          
      - name: Push docs to gh-pages branch
        run: |
            cp -r build/html /tmp
            
            git fetch
            git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git config --global user.name "$GITHUB_ACTOR"

            # Create brand new history each time
            git checkout --orphan gh-pages
            git rm -rf --cached . || true

            # Keep .git so this orphaned checkout can still be committed and pushed.
            find . -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
            # TODO: echo cookbook.opendp.org > CNAME
            cp -r /tmp/html docs

            git add --all --force
            git commit --allow-empty-message --message "$(git log $(git rev-parse origin/main) --oneline --format=%B -n1 | head -n1)"
            git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
            git push --force origin gh-pages

