on:
    pull_request:


jobs:

  docs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Make sure we get all refs
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - run: pip install -r requirements.txt

      - run: build html
