on:
    pull_request:


jobs:

  docs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # Make sure we get all refs
          fetch-depth: 0

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19.2

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.24"

      - run: uv sync --dev

      - run: uv run pre-commit run --all-files

      - run: uv run make html
